import { afterEach, describe, expect, it, vi } from 'vitest'
import {
  concatBytes,
  deriveBytes,
  equalBytes,
  generateBytes,
  normalizeBytes,
} from '../../src/util/index.js'

afterEach(() => vi.unstubAllGlobals())

describe('byte utilities', () => {
  it('normalizes every supported source into an independent copy', () => {
    const arrayBuffer = new Uint8Array([1, 2]).buffer
    const shared = new SharedArrayBuffer(2)
    new Uint8Array(shared).set([3, 4])
    const source = new Uint8Array([0, 5, 6, 0])
    const view = new DataView(source.buffer, 1, 2)

    const normalized = [
      normalizeBytes(arrayBuffer),
      normalizeBytes(shared),
      normalizeBytes(view),
      normalizeBytes([7, 8]),
    ]

    expect(normalized.map((bytes) => [...bytes])).toEqual([
      [1, 2],
      [3, 4],
      [5, 6],
      [7, 8],
    ])
    expect(normalized[0].buffer).not.toBe(arrayBuffer)
    expect(normalized[1].buffer).not.toBe(shared)
    expect(normalized[2].buffer).not.toBe(source.buffer)
  })

  it('rejects unsupported sources when SharedArrayBuffer is absent', () => {
    vi.stubGlobal('SharedArrayBuffer', undefined)
    expect(() => normalizeBytes('bytes' as never)).toThrowError(
      expect.objectContaining({ code: 'BYTE_SOURCE_EXPECTED' })
    )
  })

  it('concatenates mixed sources and describes invalid entries', () => {
    expect(concatBytes([])).toEqual(new Uint8Array())
    expect(
      concatBytes([new Uint8Array(), [1, 2], new Uint8Array([3]).buffer])
    ).toEqual(new Uint8Array([1, 2, 3]))
    expect(() => concatBytes('bad' as never)).toThrowError(
      expect.objectContaining({ code: 'CONCAT_INVALID_INPUT' })
    )
    expect(() => concatBytes([[1], 'bad' as never])).toThrowError(
      expect.objectContaining({
        code: 'CONCAT_NORMALIZE_FAILED',
        message: expect.stringContaining('index 1'),
      })
    )
  })

  it('handles a non-Error normalization failure', () => {
    class ThrowingArrayBuffer {
      static [Symbol.hasInstance](): boolean {
        return false
      }
      static isView(): boolean {
        throw 'raw failure'
      }
    }
    vi.stubGlobal('ArrayBuffer', ThrowingArrayBuffer)

    expect(() => concatBytes([{} as never])).toThrow(
      'concatBytes failed to normalize input at index 0: raw failure'
    )
  })

  it('compares equal, different, and differently sized values', () => {
    expect(equalBytes([1, 2, 3], new Uint8Array([1, 2, 3]))).toBe(true)
    expect(equalBytes([1, 2, 3], [1, 2, 4])).toBe(false)
    expect(equalBytes([1, 2], [1, 2, 3])).toBe(false)
  })

  it('derives deterministic domain-separated bytes and caches its key', async () => {
    const base = new TextEncoder().encode('base')
    const domain = new TextEncoder().encode('domain')
    const first = await deriveBytes(base, domain, 32)
    const second = await deriveBytes(base, domain, 32)
    const other = await deriveBytes(base, [1], 32)

    expect(first).toHaveLength(32)
    expect(second).toEqual(first)
    expect(other).not.toEqual(first)
  })

  it('fills and returns the generated byte buffer', () => {
    const getRandomValues = vi.fn((bytes: Uint8Array) => {
      bytes.fill(0xa5)
      return bytes
    })
    vi.stubGlobal('crypto', { getRandomValues })

    expect(generateBytes(4)).toEqual(new Uint8Array([0xa5, 0xa5, 0xa5, 0xa5]))
    expect(getRandomValues).toHaveBeenCalledOnce()
  })
})
